"""Baseline schema squash (post-remediation models).

Single replayable migration replacing historical 0001-0011. Autogenerated
from current models, then hand-edited with audit-driven deltas:
- question_bank_items ownership CHECK constraint (A2)
- partial functional indexes for FewShotSelector lookups (E2)
- exams (school_id, created_at) covering index for rate-limit counts (H8)

Revision ID: 0001_baseline_squash
Revises:
Create Date: 2026-08-25
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0001_baseline_squash'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('board', sa.String(length=50), nullable=False),
    sa.Column('class_level', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculums_board'), 'curriculums', ['board'], unique=False)
    op.create_index(op.f('ix_curriculums_class_level'), 'curriculums', ['class_level'], unique=False)
    op.create_index('ix_curriculums_lookup', 'curriculums', ['board', 'class_level', 'subject_name'], unique=True)
    op.create_index(op.f('ix_curriculums_subject_name'), 'curriculums', ['subject_name'], unique=False)
    op.create_table('plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_ngn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_exams_per_month', sa.Integer(), nullable=False),
    sa.Column('max_refinements_per_month', sa.Integer(), nullable=False),
    sa.Column('max_exports_per_month', sa.Integer(), nullable=False),
    sa.Column('max_documents_per_month', sa.Integer(), nullable=False),
    sa.Column('max_embedding_tokens_per_month', sa.Integer(), nullable=False),
    sa.Column('max_llm_tokens_per_month', sa.Integer(), nullable=False),
    sa.Column('allow_custom_templates', sa.Boolean(), nullable=True),
    sa.Column('allow_multiple_admins', sa.Boolean(), nullable=True),
    sa.Column('allow_api_access', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schools',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_personal_workspace', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('curriculum_mappings',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('local_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_mappings_curriculum_id'), 'curriculum_mappings', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_curriculum_mappings_school_id'), 'curriculum_mappings', ['school_id'], unique=False)
    op.create_table('scheme_of_works',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('subtopics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('is_exam_or_break', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheme_lookup', 'scheme_of_works', ['curriculum_id', 'term', 'week_number'], unique=True)
    op.create_index(op.f('ix_scheme_of_works_curriculum_id'), 'scheme_of_works', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_scheme_of_works_term'), 'scheme_of_works', ['term'], unique=False)
    op.create_index(op.f('ix_scheme_of_works_week_number'), 'scheme_of_works', ['week_number'], unique=False)
    op.create_table('school_settings',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('primary_llm_provider', sa.String(length=50), nullable=True),
    sa.Column('fallback_llm_provider', sa.String(length=50), nullable=True),
    sa.Column('default_total_marks', sa.String(length=3), nullable=True),
    sa.Column('exam_format', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_id', 'id')
    )
    op.create_table('school_subscriptions',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_id', sa.UUID(), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_valid_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_reset_password_token'), 'users', ['reset_password_token'], unique=False)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=False)
    op.create_table('exam_generation_proposals',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('used_by_user_id', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade_level', sa.String(length=50), nullable=False),
    sa.Column('desired_outcomes', sa.Text(), nullable=False),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('draft_questions', sa.Text(), nullable=True),
    sa.Column('term', sa.String(length=20), nullable=True),
    sa.Column('selected_weeks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade_level', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('workflow_state', sa.String(length=40), nullable=True),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('llm_call_limit', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_logs',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('log_metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_quality_snapshots',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.String(length=10), nullable=False),
    sa.Column('report_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_jobs',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_exam_id'), 'generation_jobs', ['exam_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_school_id'), 'generation_jobs', ['school_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_status'), 'generation_jobs', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('bloom_level', sa.String(length=20), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.String(length=1), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marking_scheme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_parts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('diagram_svg', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_audit_comments',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('suggested_question_text', sa.Text(), nullable=True),
    sa.Column('suggested_marking_scheme', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_bank_items',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('source_exam_id', sa.UUID(), nullable=True),
    sa.Column('source_question_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('curriculum_id', sa.UUID(), nullable=True),
    sa.Column('week_index', sa.Integer(), nullable=True),
    sa.Column('exam_type', sa.String(length=30), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade_level', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.String(length=1), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marking_scheme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_parts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('diagram_svg', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculums.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_exam_id'], ['exams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    # A2: ownership invariant — platform rows are anonymous, school rows are owned.
    sa.CheckConstraint(
        "(owner_type = 'platform' AND school_id IS NULL) OR "
        "(owner_type = 'school' AND school_id IS NOT NULL)",
        name='ck_qbi_owner_matches_school',
    )
    )
    op.create_table('question_refinements',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('refined_by_user_id', sa.UUID(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('refined_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refined_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # ---- Audit-driven hand additions -----------------------------------
    # E2: index matching FewShotSelector's case-insensitive lookups, scoped
    # to the shared platform corpus.
    op.create_index(
        'ix_qbi_platform_lookup',
        'question_bank_items',
        [sa.text('lower(subject)'), sa.text('lower(grade_level)'), 'week_index'],
        unique=False,
        postgresql_where=sa.text("owner_type = 'platform' AND is_active"),
    )
    op.create_index(
        'ix_qbi_school_browse',
        'question_bank_items',
        ['school_id', 'subject', 'grade_level'],
        unique=False,
        postgresql_where=sa.text("owner_type = 'school' AND is_active"),
    )
    # H8: covering index for the per-school daily generation COUNT.
    op.create_index(
        'ix_exams_school_created_at',
        'exams',
        ['school_id', 'created_at'],
        unique=False,
    )


def downgrade() -> None:
    # ---- Audit-driven hand additions (reversed) -------------------------
    op.drop_index('ix_exams_school_created_at', table_name='exams')
    op.drop_index('ix_qbi_school_browse', table_name='question_bank_items')
    op.drop_index('ix_qbi_platform_lookup', table_name='question_bank_items')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_refinements')
    op.drop_table('question_bank_items')
    op.drop_table('exam_audit_comments')
    op.drop_table('questions')
    op.drop_index(op.f('ix_generation_jobs_status'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_school_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_exam_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_table('exam_quality_snapshots')
    op.drop_table('usage_logs')
    op.drop_table('exams')
    op.drop_table('exam_generation_proposals')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_reset_password_token'), table_name='users')
    op.drop_table('users')
    op.drop_table('school_subscriptions')
    op.drop_table('school_settings')
    op.drop_index(op.f('ix_scheme_of_works_week_number'), table_name='scheme_of_works')
    op.drop_index(op.f('ix_scheme_of_works_term'), table_name='scheme_of_works')
    op.drop_index(op.f('ix_scheme_of_works_curriculum_id'), table_name='scheme_of_works')
    op.drop_index('ix_scheme_lookup', table_name='scheme_of_works')
    op.drop_table('scheme_of_works')
    op.drop_index(op.f('ix_curriculum_mappings_school_id'), table_name='curriculum_mappings')
    op.drop_index(op.f('ix_curriculum_mappings_curriculum_id'), table_name='curriculum_mappings')
    op.drop_table('curriculum_mappings')
    op.drop_table('schools')
    op.drop_table('plans')
    op.drop_index(op.f('ix_curriculums_subject_name'), table_name='curriculums')
    op.drop_index('ix_curriculums_lookup', table_name='curriculums')
    op.drop_index(op.f('ix_curriculums_class_level'), table_name='curriculums')
    op.drop_index(op.f('ix_curriculums_board'), table_name='curriculums')
    op.drop_table('curriculums')
    # ### end Alembic commands ###
